# Uncomment the next line to define a global platform for your project
# 
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'WYunTextDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod  'Masonry'

  target 'WYunTextDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
